### PR TITLE
Add PR template

### PR DESCRIPTION
**Pull request by ivan32rus**
dz_151221_1

### CODE REVIEW

**Review by ivan32rus — COMMENTED** [review]
add file test.py

**Review by ivan32rus — COMMENTED** [review]
Add .github/auto_assign.yml

**Review by ivan32rus — COMMENTED** [review]
Add .github/auto_assign.yml and test.py

**Review by mrgreyves — APPROVED** [review]
Здравствуйте!) Апрув!)

**Comment by ivan32rus** [comment]
+

**Comment by ivan32rus** [comment]
+

**Comment by ivan32rus** [comment]
in main

**Pull request merged**
